[tool]
[tool.poetry]
authors = ["Jinay Shah <jinayshah86@gmail.com>"]
description = ""
name = "golden ratio"
version = "0.1.0"
[tool.poetry.dependencies]
python = "^3.8"
pandas= "^1.3.4"
requests = "^2.26.0"
[tool.poetry.dev-dependencies]
pytest = "^3.4"
